### ISSUE TITLE
How to add documents once at the web screen ?

### ISSUE THREAD

**Issue by Cbhihe** [lettier/lda-topic-modeling#2]
Hi David, thanks too for yr code and the nice setup to serve the web page locally in the browser.
- I get a message that npm is deprecated and replaced on Arch Linux.  It does not prevent me from installing and running install scripts though.
- Most importantly, I'm missing something basic about how to add documents for analysis. 
Does one add them in txt format ? and whatever the format, "exactly" how ?
I've added document using their local path-names, but results make no sense as txt doc contents do not seem to be parsed. Instead the path-names appear to be parsed.  ???
- Last what would be extra nice would be adding to yr README.md file, a path to uninstall everything (for people, who like me don't want to launch a VM) after trying 'lda-topic-modelling' engine out.
Thanks.

**Comment by lettier** [comment]
Hello @Cbhihe,

- I recommend [nvm](https://github.com/creationix/nvm#install-script). This will allow you to install isolated Node environments.
- This is meant to be a web browser demo to accompany the article written. It is not a general purpose topic modeling program. The algorithm is there but the interface is not. You can add as many documents as you like but you must use the web page interface and copy and paste the text inside the text boxes. If you need to perform topic modeling on a set of documents, you can try [Gensim](https://radimrehurek.com/gensim/index.html).
- To uninstall it, you can simply remove the directory (`rm -rf lda-topic-modeling`). If you installed bower just for this tutorial, you can run `npm uninstall -g bower`. 

:+1:

**Comment by Cbhihe** [comment]
David,
Understood and thank you again. It is a nice way to show your algorithmic implementation at work. Really nicely done.
-cedric
